
INSERT into usuarios (nombre,apellido,username,email,password) VALUES ('Mario','Garcia','killer','mario.garcia@gmail.com','Mario25');
INSERT into usuarios (nombre,apellido,username,email,password) VALUES ('Gloria','Medoza Perez','la gata','gloria@gmail.com','Gloria120');
INSERT into usuarios (nombre,apellido,username,email,password) VALUES ('Pedro','Huaman Rojas','namekiano','pedro.namekiano@gmail.com','Pedro100');


INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('God of War III: Remasterizado',79.90,'Playstation 4',10,'Ambientado en el reino de la mitología griega, God of War III Remasterizado es el juego aclamado por la crítica para un solo jugador que le permite asumir el intrépido rol del ex guerrero espartano, Kratos, mientras emerge de las más oscuras profundidades del Hades para escalar hasta las cimas del Monte Olimpo y buscar su sangrienta venganza.   Armado con espadas de doble cadena y una nueva variedad de armas y magia, Kratos debe combatir con las criaturas más letales de la mitología, resolviendo al mismo tiempo complicados acertijos a lo largo de su despiadada búsqueda para destruir el Olimpo.','/img/imgJuego/ps4/god_of_war_III.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Crash Bandicoot 4: It’s About Time',249.90,'Playstation 4',8,'¡Ya era hora de que llegara un juego nuevo de Crash Bandicoot™! Crash se lanza de lleno con tus marsupiales favoritos a una aventura temporal que se cae a pedazos.
Neo Cortex y N. Tropy regresaron a las andadas y esta vez no planean darle con todo al universo, ¡su objetivo es el multiverso entero! Crash y Coco tendrán que juntar cuatro máscaras cuánticas y trastocar las leyes de la realidad para salvar el mundo.','/img/imgJuego/ps4/crash_bandicoot_4_ps4.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Everybody Dance',79.00,'Playstation 3',7,0.51,'Prepárate para detonar la fiesta! Everybody Dance te permite 40 hits de la música hip hop, pop y club. Baila y compite con tus amigos en el asombroso modo party que permite hasta 20 jugadores; demuestra tus habilidades coreografiando tus propias rutinas y reta a tus amigos a seguir tus pasos. Mantén la fiesta en su punto más alto subiendo videos y fotos de tus bailes a Facebook y Twitter. ¡Ha llegado el momento de que domines la pista de baile!','/img/imgJuego/ps3/EVERYBODY_DANCE.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Crash Bandicoot N Sane Trilogy',159.90,'Nintendo Switch',14,0.13,'Crash Bandicoot El Dr. Neo Cortex tiene un plan para hacerse con el control del mundo y quiere crear animales alterados genéticamente para imponer su mandato. Para crear a sus secuaces, Cortex secuestra a todos los animales posibles; la novia de Crash Bandicoot es una de sus víctimas. Toma el control de Crash a medida que corre, salta y gira a través de 30 niveles de acción intensa en 3 islas diferentes de Australia. Solo tú puedes ayudar a Crash a salvar a los animales, salvar a su novia y detener el complot del Dr. Cortex. Crash Bandicoot 2: Cortex Strikes Back El malvado Dr. Neo Cortex ha vuelto… ¿Para salvar al mundo? ¿Y está pidiendo ayuda a su archienemigo, Crash Bandicoot? ¿Es simplemente un intrigante plan para tentar a Crash para que le ayude en su próximo miserable plan? ¿Podrá Crash ganar de nuevo o se unirá al salvaje zoo de Cortex? Mayores ambientes en 3-D, nuevas animaciones y un elenco de pintorescos personajes.','/img/imgJuego/nintendoSwitch/CRASH_BANDICOOT_N_SANE_TRILOGY.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Little Deviants',79.90,'Playstation Vita',8,0.51,'Que el caos se desate en PS Vita. Perseguidos por los malvados Botz, los pequeños Deviants se han estrellado en el mundo de los Whoman y tú debes salvarlos. · Juega con los Little Deviants en enloquecidos minijuegos usando la pantalla táctil, el panel táctil trasero y el micrófono del sistema PS Vita y mucho más. · Con una gran cantidad de elementos por desbloquear y elementos para que vuelvas a jugarlo, necesitarás todo tu ingenio y habilidad para completar los endemoniados desafíos.','/img/imgJuego/playstationVita/LITTLE_DEVIANTS.jpg');

INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Sackboy: A Big Adventure',219.00,'Playstation 5',15,'Sackboy: A Big Adventure es un videojuego de plataformas en 3D que, basándose en el mundo de Little Big Planet y desarrollado por Sumo Digital para PlayStation 5 y PlayStation 4, nos permitirá encarnar al simpático muñeco de trapo en una serie de niveles algo más lineales llenos de puzles y el carisma ‘hecho a mano’ de otros de los coloridos títulos de la serie.','/img/imgJuego/ps5/SACKBOY_A_BIG_ADVENTURE.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Sports Champios',39.90,'Playstation 3',4,0.43,'Prepárate para competir en una serie de deportes exóticos y divertidos mientras los mejores atletas de todo el mundo se reúnen para averiguar quién es el mejor.','/img/imgJuego/ps3/SPORTS_CHAMPIONS.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Cars 3 Driven To Win',139.90,'Nintendo Switch',10,'Cars 3: Hacia la victoria es el nuevo título de conducción arcade basado en la película de Pixar. A cargo de Avalanche Software, el juego presentará seis modos de juego, un modo de desafío y batalla para jugar con amigos y familiares. De esta forma, en Cars 3: Hacia la victoria podremos deleitarnos con maniobras imposibles para conseguir la máxima puntuación posible, jugar a pantalla partida, disfrutar de carreras eliminatorias o disfrutar de una especie del modo Takedown que nos ofrecerá múltiples power-ups como si fuese un título de karts.','/img/imgJuego/nintendoSwitch/CARS_3_DRIVEN_TO_WIN.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Donkey Kong Coutry Tropical Freeze',199.90,'Nintendo Switch',15,'Las dos dimensiones son protagonistas en este nuevo título del popular gorila de Nintendo. En esta versión para Nintendo Switch el protagonista se enfrentará a diferentes pantallas en las que un ejército vikingo será el enemigo. Un trabajo realizado en alta definición con el que esta joya de lo retro vuelve a conquistar nuestras pantallas. El juego también cuenta con la presencia de Dixie Kong. Las plataformas de siempre como nunca las habías visto.','/img/imgJuego/nintendoSwitch/DONKEY_KONG_COUNTRY_TROPICAL_FREEZE.jpg');

INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Sonic & Sega All-Stars Racing',79.90,'Playstation 3',7,'En una batalla frenética hacia la bandera de cuadros, Sonic y sus amigos corren por las pistas situadas en murallas de castillos medievales, bosques exuberantes y ciudades animadas, sacados de los universos ricos y variados de Sonic y SEGA. Los personajes favoritos de los fans, Dr. Eggman, Tails, AiAi, Amigo y muchos más se unirán a Sonic en sus vehículos personalizados, revolucionando sus motores y empujándose los unos a los otros para estar en la cabeza del grupo. Cada personaje se enfrentará en la pista en una variedad de coches, motos y aviones y, en el caso de Aiai, ¡un coche-plátano! Los atajos secretos, un manejo suave y evitar los obstáculos colocados de forma estratégica son, sin duda, la mejor forma de llegar a la parte más alta del podio.','/img/imgJuego/ps3/sega_sonic_all_stars_racing_ps3_1.jpg');

INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Cyberpunk 2077',259.90,'Playstation 4',7,'Cyberpunk 2077 es una historia de acción y aventuras en mundo abierto ambientada en Night City, una megalópolis obsesionada con el poder, el glamur y la modificación corporal. Te pondrás en la piel de V, un mercenario que persigue un implante único: el secreto de la inmortalidad. Podrás personalizar las mejoras, las habilidades y el estilo del personaje mientras exploras una vasta ciudad en donde tus decisiones afectan la historia y el mundo que te rodea.','/img/imgJuego/ps4/Cyberpunk_2077.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Dragon Ball Fighter Z',159.90,'Nintendo Switch',11,0.31,'DRAGON BALL FighterZ nace de lo que hace a DRAGON BALL tan famosa: luchas espectaculares e interminables con luchadores superpoderosos. Con Arc System Works, DRAGON BALL FighterZ maximiza los gráficos de anime de alta calidad y ofrece un juego de lucha fácil de aprender pero difícil de dominar. Gráficos de anime de alta calidad, en equipo/soporte 3vs3, emocionante juego en línea, modo historia exclusivo, luchas espectaculares.','/img/imgJuego/nintendoSwitch/DRAGON_BALL_FIGHTER_Z.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Star Wars: Squadrons',219.90,'Playstation 4',13,'Domina el arte de combatir en Cazas Estelares en la auténtica experiencia de pilotaje de STAR WARS™: Squadrons. Abróchate el cinturón, vive la adrenalina de combates espaciales multijugador en primera persona con tu escuadrón y descubre qué es ser piloto en una emocionante campaña para un jugador de STAR WARS.','/img/imgJuego/ps4/star_wars_squadrons_ps4_1.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Call of Duty: Black Ops Cold War ',219.00,'Playstation 5',7,'Call of Duty: Black Ops Cold War es la nueva entrega de la famosa saga de juegos en primera persona editados por Activision para consolas y PC. Desarrollado por Treyarch, en esta ocasión viajaremos a la contienda fría de Estados Unidos con la Unión Soviética en los años ochenta, emprendiendo misiones encubiertas en la campaña para un jugador. El multijugador tendrá modos clásicos y otros especiales de esta versión más allá de la vertiente zombi, como pérdida por equipos, Dominación, Baja confirmada y Escolta VIP , siendo los dos últimos una de las grandes novedades.','/img/imgJuego/ps5/call-of-duty.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Minecraft Dungeons: Hero Edition',159.90,'Playstation 4',13,'¡Lleva Minecraft Dungeons al siguiente nivel con la edición de héroe, que incluye el juego básico y la actualización del pase de héroe!

¡Disfruta un juego totalmente nuevo de acción y aventura, inspirado en los títulos clásicos de exploración de mazmorras y basado en el universo de Minecraft! ¡Recorre las mazmorras por tu cuenta o en compañía de tus amigos! Hasta cuatro jugadores pueden combatir juntos en los niveles muy variados, llenos de acción y tesoros, mientras cumplen la misión de salvar a los aldeanos y derrotar al malvado Archillano.','/img/imgJuego/ps4/21_ps4_minecraft_dungeons_hero_edition.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Kung Fu Rider',29.90,'Playstation 3',8,'Este es Tobin, el héroe de Kung Fu Rider, un detective privado de poca monta que últimamente no tiene mucha suerte con sus casos. Lamentablemente, parece que la mala suerte no deja de perseguir a Tobin y los malos acechan al desdichado detective vaya donde vaya.','/img/imgJuego/ps3/kung_fu_rider_ps3_3.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Demon’s Souls',249.00,'Playstation 5',8,'Demon’s Souls Remake es la puesta al día del clásico videojuego de rol y acción en tercera persona de FromSoftware para PlayStation 5. Desarrollado por Bluepoint Games se trata de una ambiciosa actualización del título que inició el fenómeno Souls, que a posteriori sería seguido por Dark Souls y Bloodborne. El título, que se considera un clásico moderno y es la segunda colaboración entre Bluepoint y Japan Studio tras Shadow of the Colossus Remake, aprovechará las bondades técnicas del rompedor e innovador hardware de la nueva sobremesa de Sony.','/img/imgJuego/ps5/DEMONS_SOULS.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Minecraft',69.90,'Playstation Vita',9,0.29,'¡Imagínatelo y podrás construirlo! Minecraft, el juego aclamado por la crítica, llega a PlayStation 4. Crea tu propio mundo de juego y explora, construye y conquista. Cuando cae la noche, aparecen los monstruos, así que no dejes de buscar un refugio antes de su llegada. Sobrevivir a la noche y al mundo solo depende de tu imaginación: eres tú el que elige lo que quieres hacer. Esta edición de nueva generación incluye todas las funciones que estás esperando junto con algunas sorpresas como la posibilidad de retrasnmitir tus creaciones al mundo fácilmente pulsando el botón SHARE.','/img/imgJuego/playstationVita/MINECRAFT.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Tekken 6',79.90,'Playstation 3',7,'Tekken se ha convertido en la serie preferida por los amantes de las peleas; la sexta entrega viene repleta de muchas mejoras en su versión casera, con más de 40 personajes y un nuevo modo llamado Scenario Campaign te mantendrá ocupado por horas.','/img/imgJuego/ps3/tekken6.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Star Wars Jedi Fallen Order',139.90,'Playstation 4',9,'Star Wars Jedi: Fallen Order es un juego de acción y aventura para un jugador en tercera persona que nos trasladará a una época convulsa en la cronología de Star Wars. Desarrollado por EA y Respawn Entertainment, nos invita a encarnar a un Jedi que ha permanecido oculto a la exterminación de su religión tras la Orden 66. Nuestra misión será la de sobrevivir al recién fundado Imperio Galáctico, combatiendo contra los Inquisidores y descubriendo más de la fragmentada y proscrita Orden Jedi.','/img/imgJuego/ps4/STAR_WARS_JEDI_FALLEN_ORDER.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('DIRT 5',219.90,'Playstation 5',10,0.08,'DIRT 5 es la nueva y audaz experiencia de carreras todo terreno creada por Codemasters. Conquista impresionantes rutas globales y conduce una lista icónica de autos. ¡Experimenta un modo Carrera repleto de estrellas, pantalla dividida para cuatro jugadores, el modo de creador de arena Playgrounds y mucho más!','/img/imgJuego/ps5/DIRT_5.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Bayonetta 2',199.90,'Nintendo Switch',15,'Bayonetta 2 es, al igual que su predecesor, un hack & slash clásico, con combates, combos espectaculares, diferentes armas, pequeños puzles, bastante exploración y coleccionables. Y al igual que su predecesor, es un juego de PlatinumGames, lo que significa que siempre va a más. Incluso cuando piensas que no puede ir a más, lo consigue. Bayonetta 2 tiene un ritmo muy acertado, con zonas pausadas que fomentan la exploración y momentos que nos dejan sin respiración. Además, su historia es más fácil de seguir que la original.','/img/imgJuego/nintendoSwitch/bayonetta2.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('One Piece Pirate Warriors 3',119.90,'Playstation Vita',8,0.67,'El viaje de Luffy, desde sus comienzos hasta el cara a cara con el Demonio Celestial, Donquixote Doflamingo, será tu meta en la nueva entrega de uno de los juegos de lucha más demandados por los fans del manga/anime de One Piece. One Piece Pirate Warriors 3 vuelve para darlos la oportunidad de luchar con más personajes que nunca y disfrutar de las habilidades de los piratas más famosos que podrás encontrarte en los mares del Grand Line.','/img/imgJuego/playstationVita/ONE_PIECE_PIRATE_WARRIORS_3.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Animal Crossing: New Horizons',219.90,'Nintendo Switch',9,0.09,'Animal Crossing: New Horizons es la nueva secuela de la saga Animal Crossing para Nintendo Switch. Desarrollada por Nintendo, se trata de un capítulo más en la serie de gestión, recolección, decoración y simulación de vida de la empresa japonesa, que se ha ganado por derecho propio ser una de las más reputadas tras las exitosas entregas de Nintendo DS y Nintendo 3DS. En esta ocasión, viajaremos a una isla desierta y construiremos nuestro pueblo desde cero, mientras entablamos amistado con otros vecinos.','/img/imgJuego/nintendoSwitch/animalCrossing.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Immortals Fenyx Rising',239.90,'Playstation 4',10,'Juega en la piel de Fenyx, una nueva semideidad alada, y salva a los dioses griegos. El destino del mundo está en juego. Eres la última esperanza de los dioses.','/img/imgJuego/ps5/IMMORTALS_FENYX_RISING.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Assassin’s Creed Valhalla',279.90,'Playstation 5',10,'En Assassin’s Creed Valhalla, encarna a Eivor, un legendario saqueador vikingo en busca de la gloria Explora la edad oscura inglesa conforme atacas a tus enemigos, haces crecer tus asentamientos y construyes tu poder político.','/img/imgJuego/ps5/ASSASSINS_CREED_VALHALLA.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Crash Team Racing Nitro-Fueled',169.90,'Nintendo Switch',13,0.3,'Crash Team Racing Nitro-Fueled es la vuelta del famoso marsupial al mundo de los videojuegos y el karting. Este nuevo remake cuenta con los modos de juego, personajes, circuitos, power-ups y armas de siempre, adaptando sus controles y otros ingredientes a los nuevos tiempos. La puesta al día del mítico Crash Team Racing cuenta además con modo online y competiciones a través de internet.','/img/imgJuego/nintendoSwitch/CRASH_TEAM_RACING.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Grand Theft Auto V',79.90,'Playstation 3',6,'Los Santos: una enorme y soleada metrópolis llena de gurús de autoayuda, los aspirantes a estrellas y estrellas en decadencia que fueron alguna vez la envidia del mundo occidental ahora luchan por mantenerse a flote en una época de incertidumbre económica y TV de realidad barata.','/img/imgJuego/ps3/ps3_gta_v.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Devil May Cry 5 Special Edition',169.90,'Playstation 5',5,'Devil May Cry 5 es la quinta entrega de la serie de juegos de acción en tercera persona o ‘hack and slash’ de Capcom para Xbox One, PS4 y PC, además de PS5 y Xbox Series X/S. Retomando la saga después del lanzamiento de la cuarta parte, hace diez años, Hideaki Itsuno director del título y de la mayoría de los capítulos de las aventuras de Dante, promete una vuelta a los orígenes y una jugabilidad con distintos personajes.','/img/imgJuego/ps5/DEVIL_MAY_CRY_5_SPECIAL_EDITION.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('NBA 2K15',39.90,'Playstation 3',9,0.43,'NBA 2K15 es la última entrega del videojuego mejor valorado de simulación de la NBA líder en ventas. Tras las 70 nominaciones al premio como Juego del Año de NBA 2K14, la franquicia de NBA 2K es la mejor experiencia de simulación de baloncesto. Con el MVP de la NBA Kevin Durant en la portada y una banda sonora ecléctica seleccionada por Pharrell Williams, el artista y productor de fama internacional, NBA 2K15 salta a la cancha con unos gráficos de un realismo sin precedentes, una jugabilidad hiperrealista de la NBA y mucho más.','/img/imgJuego/ps3/NBA_2K15.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Dragon Ball Xenoverse 2',119.90,'Nintendo Switch',13,'DRAGON BALL XENOVERSE 2 sucede a DRAGON BALL XENOVERSE y viene con gráficos mejorados que sumergirán al jugador en el mayor y más detallado mundo de Dragon Ball jamás desarrollado. DRAGON BALL XENOVERSE 2 presenta una nueva ciudad y el mayor número de opciones de personalización hasta la fecha, entre otras características y mejoras especiales.','/img/imgJuego/nintendoSwitch/DRAGON BALL_XENOVERSE 2.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Crash Team Racing Nitro-Fueled',179.90,'Playstation 4',15,'¡Crash regresa al volante! Prepárate para pisar a fondo el acelerador con Crash Team Racing Nitro-Fueled. Es la experiencia auténtica de CTR y mucho más completamente remasterizada y hasta arriba de revoluciones','/img/imgJuego/ps4/crash_team_racing_ps4.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Fortnite: The Last Laugh Bundle',129.90,'Playstation 5',15,'Edición especial de Fortnite. Se trata de un pack en formato físico en colaboración con DC Comics bajo el nombre Fortnite: The Last Laugh Bundle que se centra en los villanos del mundo de los cómics.','/img/imgJuego/ps5/fortnite.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Fortnite: the Last Laugh Bundle',119.90,'Nintendo Switch',14,'Edición especial de Fortnite. Se trata de un pack en formato físico en colaboración con DC Comics bajo el nombre Fortnite: The Last Laugh Bundle que se centra en los villanos del mundo de los cómics.','/img/imgJuego/nintendoSwitch/FORTNITE_THE_LAST_LAUGH_BUNDLE.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Batman Arkham Origins',79.90,'Playstation 3',9,'PS3 BATMAN ARKHAM ORIGINS','/img/imgJuego/ps3/Batman_Arkham_Origins.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Hitman 3',239.90,'Playstation 5',10,'Hitman 3 es la nueva entrega de la saga de espionaje y sigilo de IO Interactive para PS4, PC, Xbox One, Xbox Series S/X y PS5. El episodio final de la trilogía apostará por un tono más serio y adulto que sus predecesores, con la intención de cerrar el argumento actual, y ampliando las posibilidades jugables varios enteros. Además, en las nuevas consolas tendrá ray-tracing para mejorar los gráficos y la ambientación.','/img/imgJuego/ps5/HITMAN_III.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descuento,descripcion,url) VALUES ('Assassin’s Creed The Rebil Collection',199.90 ,'Nintendo Switch',12,0.3,'Las famosas entregas de Assassin’s Creed Black Flag y Assassin’s Creed Rogue llegan como parte de una colección, esta vez para que la disfrutes en tu consola Nintendo Switch.','/img/imgJuego/nintendoSwitch/AssassinsCreeedTheRebelCollection.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Capitain Toad Treasure Tracker',139.90,'Nintendo Switch',8,'Basado en las fases especiales de Super Mario 3D World, Captain Toad nos propone controlar al Jefe del Escuadrón Toad para superar niveles en los que encontrar secretos resolviendo puzles, combinando acción, plataformas e ingenio.','/img/imgJuego/nintendoSwitch/CAPTAIN_TOAD_TREASURE_TRACKER.jpg');
INSERT INTO juegos (nombre,precio,consola,stock,descripcion,url) VALUES ('Ice Age: Scrat’s Nutty Adventure',79.90,'Playstation 4',16,'¡La ardilla dientes de sable más popular de La Era de Hielo! ¡Es la nueva aventura de Scrat! Un misterioso mecanismo en un antiguo templo scratazon atrapó su preciada posesión, y la única forma de recuperarla es aventurarse en una misión épica para encontrar las cuatro nueces de cristal legendarias, que están dispersas por toda la tierra.','/img/imgJuego/ps4/ice_age_scrats_nutty_adventure_1.jpg');

INSERT INTO juegos_en_carrito values (2,3,2);
INSERT INTO juegos_en_carrito values (2,1,3);
INSERT INTO juegos_en_carrito values (1,5,2);
INSERT INTO juegos_en_carrito values (1,8,1);
INSERT INTO juegos_en_carrito values (1,4,2);

INSERT INTO compras (id_usuario,id_juego,cant_juego,estado,fecha_pedido,fecha_entrega) VALUES (1,3,1,'entregado','2019-12-25','2020-01-01');
INSERT INTO compras (id_usuario,id_juego,cant_juego,estado,fecha_pedido,fecha_entrega) VALUES (1,1,2,'entregado','2019-12-12','2020-02-02');
INSERT INTO compras (id_usuario,id_juego,cant_juego,estado,fecha_pedido) VALUES (1,10,1,'pedido','2020-02-14');
INSERT INTO compras (id_usuario,id_juego,cant_juego,estado,fecha_pedido,fecha_entrega) VALUES (2,4,1,'entregado','2020-01-03','2020-02-20');
INSERT INTO compras (id_usuario,id_juego,cant_juego,estado,fecha_pedido) VALUES (2,7,2,'pedido','2020-02-15');
